### ISSUE TITLE
Adblocker Issue on client

### ISSUE THREAD

**Issue by GerGerApex1** [FalixNodes-Software/Desktop-App-Beta#2]
![image](https://user-images.githubusercontent.com/71051211/102483899-6b0ea900-40a0-11eb-9e04-f52b6b09289b.png)
This happened when the coins website also in the client was running
![image](https://user-images.githubusercontent.com/71051211/102484033-a01afb80-40a0-11eb-922b-b14108423a55.png)
Also this too

**Comment by LamakerOfficial** [comment]
Hi,

You have probably DNS or any program which blocks the ad.
