### ISSUE TITLE
unable to join

### ISSUE THREAD

**Issue by GamingWithMD** [FalixNodes-Software/Desktop-App-Beta#3]
can't login after clicking the discord button
![github](https://user-images.githubusercontent.com/77489690/104718519-d0f85a00-574c-11eb-81da-495b681207ae.PNG)

**Comment by KorbsStudio** [comment]
![image](https://i.imgur.com/LmZpPND.png)
Doesn't appear to be an issue on my end.

Simply try the reload button on the client tab.
