### ISSUE TITLE
Autoupdate text error

### ISSUE THREAD

**Issue by Rhys9813** [FalixNodes-Software/Desktop-App-Beta#4]
(it does happen in any window)
![error text in the bottom](https://user-images.githubusercontent.com/77929373/105635241-44434f80-5e62-11eb-929d-7990f30faba5.png)

**Comment by KorbsStudio** [comment]
Please uninstall FalixNodes Software and re-install.
Website: https://software.falixnodes.net/

Make sure you're downloading from the main repo and not beta.
