### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GamingWithMD** [FalixNodes-Software/Desktop-App-Beta#5]
![falix feedback](https://user-images.githubusercontent.com/77489690/106023841-00ae4700-60e9-11eb-9834-b02080e0c9ec.PNG)

it is not going away i try restarting

**Comment by KorbsStudio** [comment]
Uninstall it.
Download the latest version from https://software.falixnodes.net/ and install.

**Comment by GamingWithMD** [comment]
thx for your help
i wanted to ask a question if some has the bungeecord proxy and one server
linked to that on a paid host so can i link my falix server to that proxy?
